blue:
    resource: "@BlueBundle/Resources/config/routing.yml"
    prefix:   /

users_user:
    resource: "@UsersUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
